/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppLogsRouteImport } from './routes/_app.logs'
import { Route as AppCitizensRouteImport } from './routes/_app.citizens'
import { Route as AppArchivesRouteImport } from './routes/_app.archives'
import { Route as AppCitizensNewRouteImport } from './routes/_app.citizens.new'
import { Route as AppCitizensIdRouteImport } from './routes/_app.citizens.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppCitizensRoute = AppCitizensRouteImport.update({
  id: '/citizens',
  path: '/citizens',
  getParentRoute: () => AppRoute,
} as any)
const AppArchivesRoute = AppArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => AppRoute,
} as any)
const AppCitizensNewRoute = AppCitizensNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCitizensRoute,
} as any)
const AppCitizensIdRoute = AppCitizensIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCitizensRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/archives': typeof AppArchivesRoute
  '/citizens': typeof AppCitizensRouteWithChildren
  '/logs': typeof AppLogsRoute
  '/citizens/$id': typeof AppCitizensIdRoute
  '/citizens/new': typeof AppCitizensNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/archives': typeof AppArchivesRoute
  '/citizens': typeof AppCitizensRouteWithChildren
  '/logs': typeof AppLogsRoute
  '/': typeof AppIndexRoute
  '/citizens/$id': typeof AppCitizensIdRoute
  '/citizens/new': typeof AppCitizensNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/archives': typeof AppArchivesRoute
  '/_app/citizens': typeof AppCitizensRouteWithChildren
  '/_app/logs': typeof AppLogsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/citizens/$id': typeof AppCitizensIdRoute
  '/_app/citizens/new': typeof AppCitizensNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/archives'
    | '/citizens'
    | '/logs'
    | '/citizens/$id'
    | '/citizens/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/archives'
    | '/citizens'
    | '/logs'
    | '/'
    | '/citizens/$id'
    | '/citizens/new'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/archives'
    | '/_app/citizens'
    | '/_app/logs'
    | '/_app/'
    | '/_app/citizens/$id'
    | '/_app/citizens/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/citizens': {
      id: '/_app/citizens'
      path: '/citizens'
      fullPath: '/citizens'
      preLoaderRoute: typeof AppCitizensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/archives': {
      id: '/_app/archives'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof AppArchivesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/citizens/new': {
      id: '/_app/citizens/new'
      path: '/new'
      fullPath: '/citizens/new'
      preLoaderRoute: typeof AppCitizensNewRouteImport
      parentRoute: typeof AppCitizensRoute
    }
    '/_app/citizens/$id': {
      id: '/_app/citizens/$id'
      path: '/$id'
      fullPath: '/citizens/$id'
      preLoaderRoute: typeof AppCitizensIdRouteImport
      parentRoute: typeof AppCitizensRoute
    }
  }
}

interface AppCitizensRouteChildren {
  AppCitizensIdRoute: typeof AppCitizensIdRoute
  AppCitizensNewRoute: typeof AppCitizensNewRoute
}

const AppCitizensRouteChildren: AppCitizensRouteChildren = {
  AppCitizensIdRoute: AppCitizensIdRoute,
  AppCitizensNewRoute: AppCitizensNewRoute,
}

const AppCitizensRouteWithChildren = AppCitizensRoute._addFileChildren(
  AppCitizensRouteChildren,
)

interface AppRouteChildren {
  AppArchivesRoute: typeof AppArchivesRoute
  AppCitizensRoute: typeof AppCitizensRouteWithChildren
  AppLogsRoute: typeof AppLogsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArchivesRoute: AppArchivesRoute,
  AppCitizensRoute: AppCitizensRouteWithChildren,
  AppLogsRoute: AppLogsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
